2018-12-29 23:58:18,446 ERROR: Exception on /edit_profile [GET] [in /home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/michael/thundernugget/app/routes.py", line 84, in edit_profile
    if form.validate_on_submit():
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-12-29 23:58:26,639 ERROR: Exception on /edit_profile [GET] [in /home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/michael/thundernugget/app/routes.py", line 84, in edit_profile
    if form.validate_on_submit():
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-12-29 23:58:35,948 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 09:41:18,478 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 09:43:48,539 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 09:44:26,756 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 13:19:40,147 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 13:21:59,961 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 13:24:42,351 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 13:56:25,050 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 13:58:10,958 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 16:31:21,971 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 16:36:38,772 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 16:45:15,906 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 16:49:08,559 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 16:54:39,733 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 16:56:18,519 INFO: Thundernugget startup [in /home/michael/thundernugget/app/__init__.py:39]
2018-12-30 16:56:24,398 ERROR: Exception on /index [GET] [in /home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/michael/thundernugget/app/routes.py", line 28, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2018-12-30 16:56:25,684 ERROR: Exception on /index [GET] [in /home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/michael/thundernugget/app/routes.py", line 28, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2018-12-30 16:56:34,138 ERROR: Exception on /index [GET] [in /home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/michael/thundernugget/app/routes.py", line 28, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
